name: Unit Tests on push
on:
  push:
    branches:
      - develop
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Get Node environment
        uses: actions/setup-node@v2
        with:
          - node-version: 17.x
      - name: Node install
        run: npm install
      - name: Run unit tests
        run: npm test